spring.application.name=Kurs_

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/kursovaya_cargo
spring.datasource.username=postgres
spring.datasource.password=1
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

testing.app.secret = sdwlw851kftsyfds345m1234567890123456
testing.app.lifetime=7200000

youtube.api.key=AIzaSyB82tXUW1ecn0Tb6pn0iXWr_5nK8mKsF4Q
youtube.api.url=https://youtu.be/a7JM2SnlYRI?si=2R5PnfAAQfzrj8KM

yandex.maps.api.key=70d701ca-5be5-40b4-9518-15fd4b80f208

# Backup Configuration
backup.directory=backups
backup.retention.days=30